language: python
python:
  - "3.6"
# command to install dependencies
install:
  - sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable && sudo apt update && sudo apt install libgdal-dev python-gdal python3-gdal libspatialindex-dev gdal-bin libgdal1h
  - pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=sdmdl/
# command to submit code coverage to https://coveralls.io/github/naturalis/trait-geo-diverse-angiosperms?branch=master
after_success:
  - coveralls
