language: python
python:
  - "3.6"
# command to install dependencies
install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa && sudo apt update && sudo apt install gdal-bin python-gdal python3-gdal
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
