'# config file': ''
'data_path': /Users/winand.hulleman/Documents/trait-geo-diverse-angiosperms/data
'occurrence_path': /Users/winand.hulleman/Documents/trait-geo-diverse-angiosperms/data/occurrences
'result_path': /Users/winand.hulleman/Documents/trait-geo-diverse-angiosperms/results
